server:  
  port: ${PORT:9488}

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://allen-dev-vm1/tmp/config-repo
          clone-on-start: true

security:
  user:
    name: allen 
    password: Passw0rd
